// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: client_simple_hud

#include "../ui.h"

lv_obj_t *uic_bootlabel;
lv_obj_t *ui_boot = NULL;lv_obj_t *ui_mitsubishilogo = NULL;lv_obj_t *ui_bootlabel = NULL;
// event funtions
void ui_event_boot( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_hud, LV_SCR_LOAD_ANIM_FADE_ON, 100, 1, &ui_hud_screen_init);
}
}

// build funtions

void ui_boot_screen_init(void)
{
ui_boot = lv_obj_create(NULL);
lv_obj_remove_flag( ui_boot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mitsubishilogo = lv_image_create(ui_boot);
lv_image_set_src(ui_mitsubishilogo, &ui_img_mitsubishi_logo_png);
lv_obj_set_width( ui_mitsubishilogo, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_mitsubishilogo, LV_SIZE_CONTENT);   /// 240
lv_obj_set_x( ui_mitsubishilogo, 0 );
lv_obj_set_y( ui_mitsubishilogo, -20 );
lv_obj_set_align( ui_mitsubishilogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_mitsubishilogo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_mitsubishilogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_bootlabel = lv_label_create(ui_boot);
lv_obj_set_width( ui_bootlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bootlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bootlabel, 0 );
lv_obj_set_y( ui_bootlabel, -5 );
lv_obj_set_align( ui_bootlabel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_bootlabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_bootlabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_bootlabel,"PAJERO DAKAR");
lv_obj_set_style_text_align(ui_bootlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bootlabel, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_boot, ui_event_boot, LV_EVENT_ALL, NULL);
uic_bootlabel = ui_bootlabel;

}

void ui_boot_screen_destroy(void)
{
   if (ui_boot) lv_obj_del(ui_boot);

// NULL screen variables
ui_boot= NULL;
ui_mitsubishilogo= NULL;
uic_bootlabel= NULL;
ui_bootlabel= NULL;

}
