// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: client_simple_hud

#include "../ui.h"

lv_obj_t *ui_hud = NULL;lv_obj_t *ui_lbSpeed = NULL;lv_obj_t *ui_lbrpm = NULL;lv_obj_t *ui_iconserverdisconected = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_lbavgconsumption = NULL;lv_obj_t *ui_barrpm = NULL;
// event funtions

// build funtions

void ui_hud_screen_init(void)
{
ui_hud = lv_obj_create(NULL);
lv_obj_remove_flag( ui_hud, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lbSpeed = lv_label_create(ui_hud);
lv_obj_set_width( ui_lbSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbSpeed,"0");
lv_obj_set_style_text_color(ui_lbSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lbSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbSpeed, &ui_font_robotobold150, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbrpm = lv_label_create(ui_hud);
lv_obj_set_width( ui_lbrpm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbrpm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbrpm, 40 );
lv_obj_set_y( ui_lbrpm, 10 );
lv_label_set_text(ui_lbrpm,"0");
lv_obj_set_style_text_font(ui_lbrpm, &ui_font_robotoregular24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_iconserverdisconected = lv_image_create(ui_hud);
lv_image_set_src(ui_iconserverdisconected, &ui_img_icon_server_png);
lv_obj_set_width( ui_iconserverdisconected, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_iconserverdisconected, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_iconserverdisconected, -5 );
lv_obj_set_y( ui_iconserverdisconected, 5 );
lv_obj_set_align( ui_iconserverdisconected, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_iconserverdisconected, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_iconserverdisconected, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image3 = lv_image_create(ui_hud);
lv_image_set_src(ui_Image3, &ui_img_icon_fuel_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image3, 5 );
lv_obj_set_y( ui_Image3, -10 );
lv_obj_set_align( ui_Image3, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lbavgconsumption = lv_label_create(ui_hud);
lv_obj_set_width( ui_lbavgconsumption, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbavgconsumption, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbavgconsumption, 40 );
lv_obj_set_y( ui_lbavgconsumption, -8 );
lv_obj_set_align( ui_lbavgconsumption, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_lbavgconsumption,"0.00");
lv_obj_set_style_text_font(ui_lbavgconsumption, &ui_font_robotoregular24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_barrpm = lv_bar_create(ui_hud);
lv_bar_set_range(ui_barrpm, 0,6000);
lv_bar_set_value(ui_barrpm,1200,LV_ANIM_OFF);
lv_bar_set_start_value(ui_barrpm, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_barrpm, 180);
lv_obj_set_height( ui_barrpm, 10);
lv_obj_set_x( ui_barrpm, 10 );
lv_obj_set_y( ui_barrpm, 185 );
lv_obj_set_style_anim_duration(ui_barrpm, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_rotation(ui_barrpm, -900, LV_PART_MAIN| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_barrpm,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_barrpm, lv_obj_get_style_pad_right(ui_barrpm,LV_PART_MAIN) + 1, LV_PART_MAIN );

}

void ui_hud_screen_destroy(void)
{
   if (ui_hud) lv_obj_del(ui_hud);

// NULL screen variables
ui_hud= NULL;
ui_lbSpeed= NULL;
ui_lbrpm= NULL;
ui_iconserverdisconected= NULL;
ui_Image3= NULL;
ui_lbavgconsumption= NULL;
ui_barrpm= NULL;

}
