// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: client_simple_hud

#ifndef UI_HUD_H
#define UI_HUD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_hud
extern void ui_hud_screen_init(void);
extern void ui_hud_screen_destroy(void);
extern lv_obj_t *ui_hud;
extern lv_obj_t *ui_lbSpeed;
extern lv_obj_t *ui_lbrpm;
extern lv_obj_t *ui_iconserverdisconected;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_lbavgconsumption;
extern lv_obj_t *ui_barrpm;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

