[env:client_cyd]
platform  = espressif32@6.9.0
board     = esp32doit-devkit-v1
framework = arduino

lib_deps =
    lvgl/lvgl @ ^9.5.0
    lovyan03/LovyanGFX @ ^1.2.0

lib_extra_dirs = ../../lib

build_flags    =
    -I../../lib/core/include
    -I../../projects/client_cyd/include
    -I../../projects/client_cyd/src
    -I${PROJECT_LIBDEPS_DIR}/client_cyd
    -DLV_CONF_INCLUDE_SIMPLE

monitor_speed = 115200
