// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: client_simple_hud

#ifndef _CLIENT_SIMPLE_HUD_UI_H
#define _CLIENT_SIMPLE_HUD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_boot.h"
#include "screens/ui_hud.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_mitsubishi_logo_png);   // assets/mitsubishi_logo.png
LV_IMG_DECLARE( ui_img_icon_server_png);   // assets/icon_server.png
LV_IMG_DECLARE( ui_img_icon_fuel_png);   // assets/icon_fuel.png

// FONTS
LV_FONT_DECLARE( ui_font_robotobold150);
LV_FONT_DECLARE( ui_font_robotoregular24);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
