[env:client_simple_hud]
platform  = espressif32@6.9.0
board     = esp32doit-devkit-v1
framework = arduino

lib_deps =
    lvgl/lvgl @ ^9.5.0
    lovyan03/LovyanGFX @ ^1.2.0

lib_extra_dirs = ../../lib

build_src_filter =
    +<*>
    +<../ui/*.c>
    +<../ui/screens/*.c>
    +<../ui/fonts/ui_font_robotobold150.c>
    +<../ui/fonts/ui_font_robotoregular24.c>
    +<../ui/images/*.c>
    +<../ui/components/*.c>

build_flags    =
    -I../../lib/core/include
    -I../../projects/client_simple_hud/include
    -I../../projects/client_simple_hud/src
    -I../../projects/client_simple_hud/ui
    -I${PROJECT_LIBDEPS_DIR}/client_simple_hud
    -DLV_CONF_INCLUDE_SIMPLE

monitor_speed = 115200
board_build.partitions = huge_app.csv