// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: main_display

#include "../ui.h"

lv_obj_t *ui_boot = NULL;lv_obj_t *ui_mitsubishilogo = NULL;
// event funtions
void ui_event_boot( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_NONE, 100, 600, &ui_main_screen_init);
}
}

// build funtions

void ui_boot_screen_init(void)
{
ui_boot = lv_obj_create(NULL);
lv_obj_remove_flag( ui_boot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mitsubishilogo = lv_image_create(ui_boot);
lv_image_set_src(ui_mitsubishilogo, &ui_img_mitsubishi_logo_png);
lv_obj_set_width( ui_mitsubishilogo, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_mitsubishilogo, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_mitsubishilogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_mitsubishilogo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_mitsubishilogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_boot, ui_event_boot, LV_EVENT_ALL, NULL);

}

void ui_boot_screen_destroy(void)
{
   if (ui_boot) lv_obj_del(ui_boot);

// NULL screen variables
ui_boot= NULL;
ui_mitsubishilogo= NULL;

}
