// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: main_display

#ifndef _UI_COMP_PANELCOMPONENT_H
#define _UI_COMP_PANELCOMPONENT_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT panelcomponent
#define UI_COMP_PANELCOMPONENT_PANELCOMPONENT 0
#define _UI_COMP_PANELCOMPONENT_NUM 1
lv_obj_t *ui_panelcomponent_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
