// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: main_display

#ifndef _MAIN_DISPLAY_UI_COMP_HOOK_H
#define _MAIN_DISPLAY_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_panelcomponent_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
