// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: main_display

#include "ui.h"

// COMPONENT panelcomponent

lv_obj_t *ui_panelcomponent_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_panelcomponent;
cui_panelcomponent = lv_obj_create(comp_parent);
lv_obj_set_width( cui_panelcomponent, 249);
lv_obj_set_height( cui_panelcomponent, 90);
lv_obj_set_x( cui_panelcomponent, -516 );
lv_obj_set_y( cui_panelcomponent, 301 );
lv_obj_set_align( cui_panelcomponent, LV_ALIGN_TOP_RIGHT );
lv_obj_remove_flag( cui_panelcomponent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_panelcomponent, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_panelcomponent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_panelcomponent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_panelcomponent, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_secondarycolor);
ui_object_set_themeable_style_property(cui_panelcomponent, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_secondarycolor);
lv_obj_set_style_border_width(cui_panelcomponent, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANELCOMPONENT_NUM);
children[UI_COMP_PANELCOMPONENT_PANELCOMPONENT] = cui_panelcomponent;
lv_obj_add_event_cb(cui_panelcomponent, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_panelcomponent, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_panelcomponent_create_hook(cui_panelcomponent);
return cui_panelcomponent; 
}

