// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: main_display

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_lbspeed;
extern lv_obj_t *ui_lbrpm;
extern lv_obj_t *ui_lbfuelrate;
extern lv_obj_t *ui_lbconsumptionkml;
extern lv_obj_t *ui_lbavgconsumptionkml;
extern lv_obj_t *ui_lbdistancekm;
extern lv_obj_t *ui_lbbarometerpressure;
extern lv_obj_t *ui_lbambientetemperature;
extern lv_obj_t *ui_lbatgearposition;
extern lv_obj_t *ui_lbboostpressure;
extern lv_obj_t *ui_lbgearposition;
extern lv_obj_t *ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

