// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: main_display

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_background;
extern lv_obj_t *ui_lbserverstatus;
extern lv_obj_t *ui_lbtitlerpm;
extern lv_obj_t *ui_lbtitleboost;
extern lv_obj_t *ui_lbboostpressure;
extern lv_obj_t *ui_lbtitleload;
extern lv_obj_t *ui_lbengineload;
extern lv_obj_t *ui_lbtitlethr;
extern lv_obj_t *ui_lbthrottle;
extern lv_obj_t *ui_lbtitlefuel;
extern lv_obj_t *ui_lbfuelrate;
extern lv_obj_t *ui_lbtitleecon;
extern lv_obj_t *ui_lbconsumptionkml;
extern lv_obj_t *ui_lbtitleavg;
extern lv_obj_t *ui_lbavgconsumptionkml;
extern lv_obj_t *ui_lbtitletrip;
extern lv_obj_t *ui_lbdistancekm;
extern lv_obj_t *ui_lbtitlecool;
extern lv_obj_t *ui_lbcoolanttemp;
extern lv_obj_t *ui_lbtitleatf;
extern lv_obj_t *ui_lbcompass;
extern lv_obj_t *ui_lbdpfsoot;
extern lv_obj_t *ui_lbaltitude;
extern lv_obj_t *ui_lbtitlebaro;
extern lv_obj_t *ui_lbbarometerpressure;
extern lv_obj_t *ui_lbtitleamb;
extern lv_obj_t *ui_lbambientetemperature;
extern lv_obj_t *ui_lbvoltage;
extern lv_obj_t *ui_lbatgearposition;
extern lv_obj_t *ui_lbgearposition;
extern lv_obj_t *ui_lbrpm;
extern lv_obj_t *ui_lbdatetime;
extern lv_obj_t *ui_lbtitletriptime;
extern lv_obj_t *ui_lbtriptime;
extern lv_obj_t *ui_lbbrand;
extern lv_obj_t *ui_lbtitlebatteryvoltage;
extern lv_obj_t *ui_lbambienttemperature;
extern lv_obj_t *ui_iconaltitude;
extern lv_obj_t *ui_icontemperature;
extern lv_obj_t *ui_lbcompasscardial;
extern lv_obj_t *ui_icongpsarrow;
extern lv_obj_t *ui_iconcoolantstatus;
extern lv_obj_t *ui_iconhumidity;
extern lv_obj_t *ui_lbhumidity;
extern lv_obj_t *ui_lbaceleration;
extern lv_obj_t *ui_lbxaxis;
extern lv_obj_t *ui_lbyaxis;
extern lv_obj_t *ui_lbzaxis;
extern lv_obj_t *ui_lbgyrozaxis;
extern lv_obj_t *ui_lbgyroyaxis;
extern lv_obj_t *ui_lbgyroxaxis;
extern lv_obj_t *ui_lbtitlealtitude;
extern lv_obj_t *ui_lbtitlehumidity;
extern lv_obj_t *ui_lbtitleacceleration;
extern lv_obj_t *ui_lbtitlerotation;
extern lv_obj_t *ui_lbtitlerotation1;
extern lv_obj_t *ui_lbtitlerotation2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

